### ISSUE TITLE
Forced maximum analysis level

### ISSUE THREAD

**Issue by levacic** [Rockstar04/SublimeLinter-contrib-phpstan#11]
It seems that this plugin currently forces the maximum analysis level unless `SublimeLinter.linters.phpstan.level` is configured in Sublime Text.

This leads to us having to maintain and sync this level in both `phpstan.neon` (which we use to configure PHPStan in our projects) as well as the Sublime Text project file (so we would have consistent analysis both in Sublime Text and in other environments such as manually running PHPStan in the shell, or more importantly, CI environments).

Could you remove this default and just let PHPStan use its own default if no value is otherwise configured? If the default level needs to be defined for some reason, do you have any suggestions on how we can force the level defined in `phpstan.neon` to take precedence?

**Comment by levacic** [comment]
Furthermore, I would like to also respect the `paths` defined in the configuration file, ie. not lint anything not in those paths. Is there a good way to set this up?

**Comment by Rockstar04** [comment]
I threw this together as a bare bones MVP that fit my development requirements at the time. Since then I do very little PHP development. If you would like to submit a pull request to allow the plugin to find and use `phpstan.neon` I will gladly merge it in.
